### PR TITLE
updating images with transparent backgrounds

### PR DESCRIPTION
**Pull request by dcendents**
Because with the new Dark Theme Chuck Norris does not like to stick out like a sore thumb!

This is the best I could do with my limited skills and paint.net.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@dcendents I am a bit concerned about the resulting image sizes. Do we really need a 32bit depth? I switched the image to 8-but depth, and it did not impact the visual quality. At the same time the size dropped from 192Kb from 66 Kb. It is still 3 times higher than JPEG, so likely there are more optimization opportunities

CC @timja since it is for Dark Theme compatibility.

**Comment by dcendents** [comment]
Hi @oleg-nenashev,

Well the jpg quality is quite poor and it was really hard to sperate the background from the image, especially the white one in kimono, so I had to find them on Internet. Which explains the resolution and size difference. I did not think it mattered that much, once your browser has cached it.

Anyway I reduced the image size and DPI and the bit depth. Now they are of similar size as the jpg were but not as nice as before, there is still a bit of white showing around on a dark background that the higher bit depth was smoothing.

All in all this is still an improvement.

Cheers,

**Comment by oleg-nenashev** [comment]
@dcendents Thank a lot for the patch! Was no need to go down to the same size as before, though it should be fine. I suggest we merge/release this version, and then revisit if needed

**Review by oleg-nenashev — APPROVED** [review]
👍 Thanks! I doubt there are any upcoming changes to this plugin, so I will release it right away

**Pull request merged**
